""" 2-category of finitely presented categories.

This module is for the 2-category **Cat** what the module [`FinSets`](@ref) is
for the category **Set**: a finitary, combinatorial setting where explicit
calculations can be carried out. We emphasize that the prefix `Fin` means
"finitely presented," not "finite," as finite categories are too restrictive a
notion for many purposes. For example, the free category on a graph is finite if
and only if the graph is DAG, which is a fairly special condition. This usage of
`Fin` is also consistent with `FinSet` because for sets, being finite and being
finitely presented are equivalent.
"""
module FinCats
export FinCat, FinCatGraph, PreorderFinCat, Path, ob_generator, hom_generator,
  ob_generator_name, hom_generator_name, ob_generators, hom_generators,
  equations, is_discrete, is_free, graph, edges, src, tgt, presentation, gentype, decompose

using StructEquality
using Reexport

using GATlab
import GATlab: equations, getvalue

import .....Theories: dom, codom, id, compose, ⋅, ∘
using .....Graphs
import .....Graphs: Graph, NamedGraph, src, tgt


import ..Categories: ob_set, hom_set
using ..Categories: CatImpl, ThCategoryExplicitSets

using ....BasicSets: FinSet, AbsSet, SetOb
using ...Paths: Path

# Theory of Finite Categories
#############################

"""
A FinCat has an unbiased `compose` method which must convert a path of 
generators into a Hom. (It is ok for Hom=Path, in which case this is a no-op).
One should also be able to express a hom in terms of generators (though this 
need not be unique, so `decompose` is a one-sided inverse).

This interface does NOT specify the fact that any implementation of FinCat 
should specify `equations`.
"""
@theory ThFinCat begin
  Ob::TYPE
  Hom(dom::Ob,codom::Ob)::TYPE; 
  id(a::Ob)::Hom(a,a)

  Gen(src::Ob,tgt::Ob)::TYPE; 
  
  Path′(p_src::Ob, p_tgt::Ob)::TYPE;
  compose(vgen::Path′(a,b))::Hom(a,b) ⊣ [(a,b)::Ob]
  decompose(h::Hom(a,b))::Path′(a,b) ⊣ [(a,b)::Ob]

  Set′::TYPE  # FinSet
  ob_set()::Set′
  gen_set()::Set′

  # compose(emptyPath(a)) == id(a) ⊣ [a::Ob]
  # compose(decompose(h)) == h ⊣ [(x,y)::Ob, a::Hom(x,y)]
  # compose(a ++ b) = compose(compose(a), compose(b)) ⊣ [a::Path(x,y), b::Path(y,z)]
end

""" Any type which subtypes FinCatImpl is expected to implement ThFinCat """
abstract type FinCatImpl{Ob,Hom,Gen} <: Model{
  Tuple{Ob,Hom,Gen,Path{Ob,Gen},FinSet}} end
  
# Wrapper type for models of `ThFinCat`
#######################################

""" 
Wrapper type for models of `ThFinCat`
  
A finitely presented (but not necessarily finite!) category.
"""
@struct_hash_equal struct FinCat{Ob,Hom} <: CatImpl{Ob,Hom}
  impl::FinCatImpl{Ob,Hom}
  function FinCat(impl::FinCatImpl{Ob,Hom,Gen}) where {Ob,Hom,Gen}
    implements(impl, ThFinCat) || error("Model isn't a FinCat")
    new{Ob,Hom}(impl)
  end
end

getvalue(f::FinCat) = f.impl

# Access model methods
#---------------------

id(f::FinCat, x) = ThFinCat.id[getvalue(f)](x)

dom(f::FinCat, x)::Cat = ThFinCat.dom[getvalue(f)](x)

codom(f::FinCat, x)::Cat = ThFinCat.codom[getvalue(f)](x)

src(f::FinCat, x) = ThFinCat.src[getvalue(f)](x)

tgt(f::FinCat, x) = ThFinCat.tgt[getvalue(f)](x)

compose(C::FinCat, x::Path) = ThFinCat.compose[getvalue(C)](x)

decompose(C::FinCat, x) = ThFinCat.decompose[getvalue(C)](x)

ob_set(f::FinCat) = ThFinCat.ob_set[getvalue(f)]()

gen_set(f::FinCat) = ThFinCat.gen_set[getvalue(f)]()

function hom_set(f::FinCat)
  T = supertype(typeof(getvalue(f))) # Model{Tuple{Ob,Hom,Gen}}
  SetOb(T.parameters[1].parameters[2])
end

# Other methods
#--------------

Base.show(io::IO, C::FinCat) = show(io, getvalue(C))

""" synonym for `ob_set` """
ob_generators(f::FinCat)::FinSet = ob_set(f)

""" synonym for `gen_set` """
hom_generators(f::FinCat)::FinSet = gen_set(f)

gentype(f::FinCat) = eltype(hom_generators(f))

""" Is the category discrete?

A category is *discrete* if it is has no non-identity morphisms.
"""
is_discrete(C::FinCat) = isempty(hom_generators(C))

# Second clause should be superfluous, but we'll include it anyway.
Base.isempty(C::FinCat) = isempty(ob_generators(C)) && isempty(hom_generators(C))

# Equations #

""" Is the category freely generated?
"""
is_free(C::FinCat) = isempty(equations(C))

equations(f::FinCat) = equations(getvalue(f))

equations(::FinCatImpl) = [] # by default, assume none

# Conversion to Graphs #

"""
Graph underlying a finitely presented category whose object and hom generators 
are indexable, other than one explicitly generated by a graph.
"""
function NamedGraph(C::FinCat)
  Ob, Gen = obtype(C), gentype(C)
  g = NamedGraph{Ob,Gen}()
  obgens = ob_generators(C)
  homgens = hom_generators(C)
  add_vertices!(g,length(obgens);vname=obgens)
  s(f) = only(indexin([dom(C,f)],obgens))
  t(f) = only(indexin([codom(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens];
              ename=homgens) 
  g
end

function Graph(C::FinCat) 
  g = Graph()
  obgens = collect(ob_generators(C))
  homgens = collect(hom_generators(C))
  add_vertices!(g,length(obgens))
  s(f) = only(indexin([src(C,f)],obgens))
  t(f) = only(indexin([tgt(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens]) 
  g
end

# Implementation of ThCategoryExplicitSets
##########################################
@instance ThCategoryExplicitSets{Ob,Hom,AbsSet} [model::FinCat{Ob,Hom}
                                                ] where {Ob,Hom} begin

  dom(f::Hom) = dom(getvalue(model), f)

  codom(f::Hom) = codom(getvalue(model), f)

  id(x::Ob) = id(model, x)

  compose(f::Hom, g::Hom) = 
    compose(model, vcat(decompose(model, f), decompose(model, g)))

  ob_set() = ob_set(model)

  hom_set() = hom_set(model)
end


# Implementations 
#################

include("FinCatImpls/PathCats.jl")
include("FinCatImpls/PreorderCat.jl")
include("FinCatImpls/OpFinCat.jl")
include("FinCatImpls/FinCatGraphs.jl")
include("FinCatImpls/FinCatPres.jl")

@reexport using .PathCats
@reexport using .PreorderCat
@reexport using .OpFinCat
@reexport using .FinCatGraphs
@reexport using .FinCatPres

end # module
