""" 2-category of finitely presented categories.

This module is for the 2-category **Cat** what the module [`FinSets`](@ref) is
for the category **Set**: a finitary, combinatorial setting where explicit
calculations can be carried out. We emphasize that the prefix `Fin` means
"finitely presented," not "finite," as finite categories are too restrictive a
notion for many purposes. For example, the free category on a graph is finite if
and only if the graph is DAG, which is a fairly special condition. This usage of
`Fin` is also consistent with `FinSet` because for sets, being finite and being
finitely presented are equivalent.
"""
module FinCats
export FinCat, FinCatGraph, PreorderFinCat, Path, ob_generator, hom_generator,
  ob_generator_name, hom_generator_name, ob_generators, hom_generators,
  equations, is_discrete, is_free, graph, edges, src, tgt, presentation

using StructEquality
using Reexport
using StaticArrays: SVector

using ACSets
using GATlab
import GATlab: equations, getvalue
using ....Theories: ThSchema, ThPointedSetSchema, AttrTypeExpr, FreeSchema
import ....Theories: dom, codom, id, compose, ⋅, ∘
using ....Graphs
import ....Graphs: Graph, NamedGraph, edges, src, tgt, enumerate_paths
@reexport using ..Categories
import ..Categories: ob, hom, ob_map, hom_map, component, op
using ..Categories: AbsCat, AbsFunctor, AbsFunctorImpl, ThFunctor
using ..FreeDiagrams: AbstractFreeDiagram
import ..FreeDiagrams: cone_objects, cocone_objects, diagram_type, FreeDiagram

# Categories
############

"""
A FinCat extends the category interface with nullary functions to list the 
ob/hom generators.

This interface does NOT specify the fact that any implementation of FinCat 
should specify `equations`.
"""
@theory ThFinCat <: ThCategory begin
  Gen(gen_dom::Ob,gen_codom::Ob)::TYPE
  Any′::TYPE 
  singleton(g::Gen(a,b))::Hom(a,b) ⊣ [(a,b)::Ob]
  ob_generators()::Any′  # Vector{Ob}
  hom_generators()::Any′ # Vector{Gen} 
end

const M{Ob,Hom,Gen} = Model{Tuple{Ob,Hom,Gen,Any}}

abstract type FinCatImpl{Ob,Hom,Gen} <: M{Ob,Hom,Gen} end

""" A finitely presented (but not necessarily finite!) category.
"""
@struct_hash_equal struct FinCat{Ob,Hom,Gen} <: AbsCat{Ob,Hom}
  impl::FinCatImpl{Ob,Hom,Gen}
  function FinCat(impl::FinCatImpl{Ob,Hom,Gen}) where {Ob,Hom,Gen}
    implements(impl, ThFinCat) || error("Model isn't a FinCat")
    new{Ob,Hom,Gen}(impl)
  end
end

getvalue(f::FinCat) = f.impl

Base.show(io::IO, C::FinCat) = show(io, getvalue(C))

equations(f::FinCat) = equations(getvalue(f))

equations(::FinCatImpl) = [] # by default, assume none

function dom(f::FinCat{Ob,Hom,Gen}, x::Gen)::Ob where {Ob,Hom,Gen} 
  dom(f, singleton(f, x))
end

function codom(f::FinCat{Ob,Hom,Gen}, x::Gen)::Ob where {Ob,Hom,Gen} 
  codom(f, singleton(f, x))
end

function singleton(f::FinCat{Ob,Hom,Gen}, x::Gen)::Hom where {Ob,Hom,Gen} 
  ThFinCat.singleton[getvalue(f)](x)
end

function compose(C::FinCat{Ob,Hom,Gen}, f::Hom, g::Gen) where {Ob,Hom,Gen} 
  compose(C, f, singleton(C,g))
end

function compose(C::FinCat{Ob,Hom,Gen}, f::Gen, g::Hom) where {Ob,Hom,Gen} 
  compose(C, singleton(C,f), g)
end

function compose(C::FinCat{Ob,Hom,Gen}, fs::Vector{Gen}) where {Ob,Hom,Gen} 
  compose(C, singleton.(Ref(C), fs))
end

function compose(C::FinCat{Ob,Hom,Gen}, f::Gen, g::Gen) where {Ob,Hom,Gen} 
  compose(C, singleton(C, f), singleton(C,g))
end

function ob_generators(f::FinCat{O,H,G})::AbstractVector{O} where {O,H,G} 
  ThFinCat.ob_generators[getvalue(f)]()
end

function hom_generators(f::FinCat{O,H,G})::AbstractVector{G} where {O,H,G} 
  ThFinCat.hom_generators[getvalue(f)]()
end

# TODO replace with `ob_generator` / `hom_generator` with official 
# `has_ob` and `has_hom` + `Bool` in the interface?

""" Is the category discrete?

A category is *discrete* if it is has no non-identity morphisms.
"""
is_discrete(C::FinCat) = isempty(hom_generators(C))

""" Is the category freely generated?
"""
is_free(C::FinCat) = isempty(equations(C))


# Second clause should be superfluous but we'll include it anyway.
Base.isempty(C::FinCat) = isempty(ob_generators(C)) && isempty(hom_generators(C))

# Converting FinCats to Graphs
#-----------------------------

"""
Graph underlying a finitely presented category whose object and hom generators 
are indexable, other than one explicitly generated by a graph.
"""
function NamedGraph(C::FinCat{Ob,<:Any,Gen}) where {Ob,Gen} 
  g = NamedGraph{Ob,Gen}()
  obgens = ob_generators(C)
  homgens = hom_generators(C)
  add_vertices!(g,length(obgens);vname=obgens)
  s(f) = only(indexin([dom(C,f)],obgens))
  t(f) = only(indexin([codom(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens];
              ename=homgens) 
  g
end

function Graph(C::FinCat) 
  g = Graph()
  obgens = ob_generators(C)
  homgens = hom_generators(C)
  add_vertices!(g,length(obgens))
  s(f) = only(indexin([dom(C,f)],obgens))
  t(f) = only(indexin([codom(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens]) 
  g
end

graph(C::FinCat{Int,<:Any, Int}) = Graph(C)

graph(C::FinCat) = NamedGraph(C)


# Implementations 
#################

include("FinCatImpls/PreorderCat.jl")

include("FinCatImpls/OpFinCat.jl")

include("FinCatImpls/FinCatGraph.jl")

include("FinCatImpls/FinCatPres.jl")




end
