""" 2-category of finitely presented categories.

This module is for the 2-category **Cat** what the module [`FinSets`](@ref) is
for the category **Set**: a finitary, combinatorial setting where explicit
calculations can be carried out. We emphasize that the prefix `Fin` means
"finitely presented," not "finite," as finite categories are too restrictive a
notion for many purposes. For example, the free category on a graph is finite if
and only if the graph is DAG, which is a fairly special condition. This usage of
`Fin` is also consistent with `FinSet` because for sets, being finite and being
finitely presented are equivalent.
"""
module FinCats
export FinCat, FinCatGraph, PreorderFinCat, Path, ob_generator, hom_generator,
  ob_generator_name, hom_generator_name, ob_generators, hom_generators,
  equations, is_discrete, is_free, graph, edges, src, tgt, presentation

using StructEquality
using Reexport
using StaticArrays: SVector

using ACSets
using GATlab
import GATlab: equations, getvalue
using ....Theories: ThSchema, ThPointedSetSchema, AttrTypeExpr, FreeSchema
import ....Theories: dom, codom, id, compose, ⋅, ∘
using ....Graphs
import ....Graphs: Graph, NamedGraph, edges, src, tgt, enumerate_paths
@reexport using ..Categories
import ..Categories: ob, hom, ob_map, hom_map, component, op
using ..Categories: AbsCat, AbsFunctor, AbsFunctorImpl, ThFunctor
using ..FreeDiagrams: AbstractFreeDiagram
import ..FreeDiagrams: cone_objects, cocone_objects, diagram_type, FreeDiagram

# Categories
############

"""
A FinCat extends the category interface with nullary functions to list the 
ob/hom generators.

This interface does NOT specify the fact that any implementation of FinCat 
should specify `equations`.
"""
@theory ThFinCat <: ThCategory begin
  Gen(gen_dom::Ob,gen_codom::Ob)::TYPE
  Any′::TYPE 
  singleton(g::Gen(a,b))::Hom(a,b) ⊣ [(a,b)::Ob]
  ob_generators()::Any′  # Vector{Ob}
  hom_generators()::Any′ # Vector{Gen} 
end

const M{Ob,Hom,Gen} = Model{Tuple{Ob,Hom,Gen,Any}}

abstract type FinCatImpl{Ob,Hom,Gen} <: M{Ob,Hom,Gen} end

""" A finitely presented (but not necessarily finite!) category.
"""
@struct_hash_equal struct FinCat{Ob,Hom,Gen} <: AbsCat{Ob,Hom}
  impl::FinCatImpl{Ob,Hom,Gen}
  function FinCat(impl::FinCatImpl{Ob,Hom,Gen}) where {Ob,Hom,Gen}
    implements(impl, ThFinCat) || error("Model isn't a FinCat")
    new{Ob,Hom,Gen}(impl)
  end
end

getvalue(f::FinCat) = f.impl

Base.show(io::IO, C::FinCat) = show(io, getvalue(C))

equations(f::FinCat) = equations(getvalue(f))

equations(::FinCatImpl) = [] # by default, assume none

function dom(f::FinCat{Ob,Hom,Gen}, x::Gen)::Ob where {Ob,Hom,Gen} 
  dom(f, singleton(f, x))
end

function codom(f::FinCat{Ob,Hom,Gen}, x::Gen)::Ob where {Ob,Hom,Gen} 
  codom(f, singleton(f, x))
end

function singleton(f::FinCat{Ob,Hom,Gen}, x::Gen)::Hom where {Ob,Hom,Gen} 
  ThFinCat.singleton[getvalue(f)](x)
end

function compose(C::FinCat{Ob,Hom,Gen}, f::Hom, g::Gen) where {Ob,Hom,Gen} 
  compose(C, f, singleton(C,g))
end

function compose(C::FinCat{Ob,Hom,Gen}, f::Gen, g::Hom) where {Ob,Hom,Gen} 
  compose(C, singleton(C,f), g)
end

function compose(C::FinCat{Ob,Hom,Gen}, fs::Vector{Gen}) where {Ob,Hom,Gen} 
  compose(C, singleton.(Ref(C), fs))
end

function compose(C::FinCat{Ob,Hom,Gen}, f::Gen, g::Gen) where {Ob,Hom,Gen} 
  compose(C, singleton(C, f), singleton(C,g))
end

function ob_generators(f::FinCat{O,H,G})::AbstractVector{O} where {O,H,G} 
  ThFinCat.ob_generators[getvalue(f)]()
end

function hom_generators(f::FinCat{O,H,G})::AbstractVector{G} where {O,H,G} 
  ThFinCat.hom_generators[getvalue(f)]()
end

# TODO replace with `ob_generator` / `hom_generator` with official 
# `has_ob` and `has_hom` + `Bool` in the interface?

""" Is the category discrete?

A category is *discrete* if it is has no non-identity morphisms.
"""
is_discrete(C::FinCat) = isempty(hom_generators(C))

""" Is the category freely generated?
"""
is_free(C::FinCat) = isempty(equations(C))


# Second clause should be superfluous but we'll include it anyway.
Base.isempty(C::FinCat) = isempty(ob_generators(C)) && isempty(hom_generators(C))

# Converting FinCats to Graphs
#-----------------------------

"""
Graph underlying a finitely presented category whose object and hom generators 
are indexable, other than one explicitly generated by a graph.
"""
function NamedGraph(C::FinCat{Ob,<:Any,Gen}) where {Ob,Gen} 
  g = NamedGraph{Ob,Gen}()
  obgens = ob_generators(C)
  homgens = hom_generators(C)
  add_vertices!(g,length(obgens);vname=obgens)
  s(f) = only(indexin([dom(C,f)],obgens))
  t(f) = only(indexin([codom(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens];
              ename=homgens) 
  g
end

function Graph(C::FinCat) 
  g = Graph()
  obgens = ob_generators(C)
  homgens = hom_generators(C)
  add_vertices!(g,length(obgens))
  s(f) = only(indexin([dom(C,f)],obgens))
  t(f) = only(indexin([codom(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens]) 
  g
end

graph(C::FinCat{Int,<:Any, Int}) = Graph(C)

graph(C::FinCat) = NamedGraph(C)

###################
# Implementations #
###################

# Preorders
###########

"""
In order to avoid type ambiguities, generators and morphisms need different
types. 
"""
@struct_hash_equal struct PreorderFinCat{Ob} <: FinCatImpl{Ob,Pair{Int,Int},Pair{Int,Int}}
  gens::Vector{Ob}
  gendict::Dict{Ob,Int}
  rel::Set{Pair{Int,Int}}
  function PreorderFinCat(p::AbstractVector{Pair{Ob,Ob}}; vals=nothing) where Ob
    # compute transitive closure
    vals = isnothing(vals) ? unique([first.(p); last.(p)]) : vals
    valdict = Dict(v=>i for (i,v) in enumerate(vals))
    m(f) = [valdict[f(x)] for x in p]
    G = Graph(length(vals))
    add_edges!(G, m(first), m(last))
    ps = enumerate_paths(G)
    r = [s=>t for (s,t,e) in zip(ps[:src], ps[:tgt], ps[:eprops]) 
         if s==t || !isempty(e)]
    new{Ob}(vals, valdict, Set(r))
  end
end

PreorderFinCat(p::AbstractVector{Tuple{Ob,Ob}}; vals=nothing) where Ob = 
  PreorderFinCat([x=>y for (x,y) in p]; vals)

PreorderFinCat(p::T, q::T; vals=nothing) where {Ob, T<:AbstractVector{Ob}} = 
  PreorderFinCat(collect(zip(p,q)); vals)

@instance ThFinCat{Ob, Pair{Int,Int}, Pair{Int,Int}, Any} [model::PreorderFinCat{Ob}
                                      ] where {Ob} begin
  dom(f::Pair{Int,Int})::Ob = model.gens[first(f)]

  codom(f::Pair{Int,Int})::Ob = model.gens[last(f)]

  id(x::Ob)::Pair{Int,Int} = let i = model.gens[x]; i => i end

  compose(f::Pair{Int,Int}, g::Pair{Int,Int})::Pair{Int,Int} = (f[1]=> g[2])

  singleton(f::Pair{Int,Int})::Pair{Int,Int} = f

  ob_generators() = model.gens

  hom_generators() = collect(model.rel)
end


# Opposite FinCats
##################

@struct_hash_equal struct OppositeFinCat{Ob,Hom,Gen} <: FinCatImpl{Ob,Hom,Gen}
  val::FinCat{Ob,Hom,Gen}
end

getvalue(o::OppositeFinCat) = o.val

@instance ThFinCat{Ob, Hom, Gen, Any} [model::OppositeFinCat{Ob,Hom,Gen}
                                      ] where {Ob,Hom,Gen} begin
  dom(f::Hom)::Ob = codom(getvalue(model), f)

  codom(f::Hom)::Ob = dom(getvalue(model), f)

  id(x::Ob)::Hom = id(getvalue(model), x)

  compose(f::Hom, g::Hom)::Hom = compose(getvalue(model), g, f)

  singleton(f::Gen)::Hom = singleton(getvalue(model), f)

  ob_generators() = ob_generators(getvalue(model))

  hom_generators() = hom_generators(getvalue(model))
end

equations(C::OppositeFinCat) = 
  map(x->reverse(x.first)=>reverse(x.second),equations(getvalue(C)))

decompose(C::OppositeFinCat{<:Any,H}, f::H) where H = 
  reverse(decompose(getvalue(C), f))

function op(f::FinCat)
  v = getvalue(f) 
  v isa OppositeFinCat && return getvalue(v)  # optimization
  FinCat(OppositeFinCat(f))
end

# Categories on graphs
######################

# Paths in graphs
#----------------

""" Path in a graph.

The path is allowed to be empty but always has definite start and end points
(source and target vertices).
"""
@struct_hash_equal struct Path{V,E,Edges<:AbstractVector{E}}
  edges::Edges
  src::V
  tgt::V
end
edges(path::Path) = path.edges
src(path::Path) = path.src
tgt(path::Path) = path.tgt

function Path(g::HasGraph, es::AbstractVector)
  !isempty(es) || error("Nonempty edge list needed for nontrivial path")
  all(e -> has_edge(g, e), es) || error("Path has edges not contained in graph")
  Path(es, src(g, first(es)), tgt(g, last(es)))
end

function Path(g::HasGraph, e)
  has_edge(g, e) || error("Edge $e not contained in graph $g")
  Path(SVector(e), src(g,e), tgt(g,e))
end

function Base.empty(::Type{Path}, g::HasGraph, v::T) where T
  has_vertex(g, v) || error("Vertex $v not contained in graph $g")
  Path(SVector{0,T}(), v, v)
end

Base.reverse(p::Path) = Path(reverse(edges(p)), tgt(p), src(p))

function Base.vcat(p1::Path, p2::Path)
  tgt(p1) == src(p2) ||
    error("Path start/end points do not match: $(tgt(p1)) != $(src(p2))")
  Path(vcat(edges(p1), edges(p2)), src(p1), tgt(p2))
end

coerce_path(::HasGraph, path::Path) = path

coerce_path(g::HasGraph, x) = Path(g, x)

function Base.show(io::IO, path::Path)
  print(io, "Path(")
  show(io, edges(path))
  print(io, ": $(src(path)) → $(tgt(path)))")
end

# Common interface for NamedGraphs and other graphs
#--------------------------------------------------
get_ob(g::NamedGraph, v) = g[v, :vname]

get_ob(::HasGraph, v) = v 

get_hom(::NamedGraph, e) = g[e, :ename]

get_hom(g::HasGraph, e) = e


# FinCatGraph
#------------

""" Abstract type for category backed by finite generating graph.

Edges are presumably morphism generators, and paths are the morphisms.
"""
abstract type FinCatGraph{G,V,E} <: FinCatImpl{V,Path{V,E},E} end

@instance ThFinCat{V,Path{V,E},E,Any} [model::FinCatGraph{G,V,E}] where {G,V,E} begin
  dom(f::Path{V,E}) = get_ob(getvalue(model), src(f))

  codom(f::Path{V,E}) = get_ob(getvalue(model),tgt(f))

  id(x::V) = empty(Path, getvalue(model), x)

  compose(f::Path{V,E},g::Path{V,E}) = vcat(f, g)

  singleton(f::E) = Path(getvalue(model), f)

  ob_generators() = let m = getvalue(model); get_ob.(Ref(m), vertices(m)) end

  hom_generators() = let m = getvalue(model); get_hom.(Ref(m), edges(m)) end
end


function Base.show(io::IO, C::FinCatGraph)
  print(io, "FinCat(")
  show(io, getvalue(C))
  print(io, ", [")
  join(io, equations(C), ", ")
  print(io, "])")
end

decompose(::FinCatGraph, path::Path) = edges(path)

# Free category on graph
#-----------------------

""" Free category generated by a finite graph.

The objects of the free category are vertices in the graph and the morphisms are
(possibly empty) paths.
"""
@struct_hash_equal struct FreeCatGraph{G<:HasGraph, V, E} <: FinCatGraph{G,V,E}
  graph::G
end

function FreeCatGraph(n::T) where {V,E,T<:NamedGraph{V,E}}
  FreeCatGraph{T,V,E}(n)
end

function FreeCatGraph(n::T) where {T<:HasGraph}
  FreeCatGraph{T, Int, Int}(n)
end

getvalue(g::FreeCatGraph) = g.graph

function Base.show(io::IO, C::FreeCatGraph)
  print(io, "FinCat(")
  show(io, getvalue(C))
  print(io, ")")
end

# Category on graph with equations
#---------------------------------

""" Category presented by a finite graph together with path equations.

The objects of the category are vertices in the graph and the morphisms are
paths, quotiented by the congruence relation generated by the path equations.
See (Spivak, 2014, *Category theory for the sciences*, §4.5).
"""
@struct_hash_equal struct FinCatGraphEq{
    G<:HasGraph,V,E,Eqs<:AbstractVector{<:Pair}} <: FinCatGraph{G, V, E}
  graph::G
  equations::Eqs
end

getvalue(f::FinCatGraphEq) = f.graph

equations(C::FinCatGraphEq) = C.equations

function FinCatGraph(g::G, eqs::AbstractVector=[]) where {G<:HasGraph}
  isempty(eqs) && return FreeCatGraph(g)
  eqs = process_eqs(g, eqs)
  FinCatGraphEq{G, Int,Int,typeof(eqs)}(g, eqs)
end

function FinCatGraph(g::NamedGraph{V,E}, eqs::AbstractVector=[]) where {V,E}
  isempty(eqs) && return FreeCatGraph(g)
  eqs = process_eqs(g, eqs)
  FinCatGraphEq{G, V,E,typeof(eqs)}(g, eqs)
end

FinCat(g::HasGraph, args...; kw...) = FinCat(FinCatGraph(g, args...; kw...))

process_eqs(g, eqs) = map(eqs) do eq
  lhs, rhs = coerce_path(g, first(eq)), coerce_path(g, last(eq))
  (src(lhs) == src(rhs) && tgt(lhs) == tgt(rhs)) ||
    error("Paths $lhs and $rhs in equation do not have equal (co)domains")
  lhs => rhs
end

# Symbolic categories
#####################

""" Category defined by a `Presentation` object.

The presentation type can, of course, be a category (`Theories.Category`). It
can also be a schema (`Theories.Schema`). In this case, the schema's objects and
attribute types are regarded as the category's objects and the schema's
morphisms, attributes, and attribute types as the category's morphisms (where
the attribute types are identity morphisms). When the schema is formalized as a
profunctor whose codomain category is discrete, this amounts to taking the
collage of the profunctor.
"""
@struct_hash_equal struct FinCatPresentation{T
    } <: FinCatImpl{GATExpr{:generator},GATExpr,GATExpr{:generator}}
  presentation::Presentation{T}
end

getvalue(f::FinCatPresentation) = f.presentation

FinCat(pres::Presentation, args...; kw...) =
  FinCat(FinCatPresentation(pres, args...; kw...))

function FinCatPresentation(pres::Presentation{ThPointedSetSchema.Meta.T})
  S = pres.syntax
  Ob = Union{S.Ob, S.AttrType}
  Hom = Union{S.Hom, S.Attr, S.AttrType}
  FinCatPresentation{ThPointedSetSchema.Meta.T,Ob,Hom}(pres)
end

"""
Computes the graph generating a finitely presented category. Ignores any attribute
side and any equations. Optionally returns the mappings from generators to their indices
in the resulting graph.
"""
presentation(C::FinCatPresentation) = C.presentation

# Should Ob = Gen = GATExpr{:generator} and Hom = GATExpr{:compose}
@instance ThFinCat{GATExpr{:generator}, GATExpr, GATExpr{:generator}, Any
                  } [model::FinCatPresentation{T}] where {T} begin
  dom(f::GATExpr)::Ob = dom(getvalue(model), f)

  codom(f::GATExpr)::Ob = codom(getvalue(model), f)

  id(x::GATExpr{:generator})::GATExpr = id(getvalue(model), x)

  compose(f::GATExpr, g::GATExpr)::GATExpr = compose(getvalue(model), g, f)

  singleton(f::GATExpr{:generator})::GATExpr = f

  function ob_generators() 
    P = getvalue(model)
    haskey(P.generators, :AttrType) || return generators(P, :Ob)
    vcat(generators(P, :Ob), generators(P, :AttrType))
  end

  function hom_generators()
    P = getvalue(model) 
    haskey(P.generators, :Attr) || return generators(P, :Hom)
    vcat(generators(P, :Hom), generators(P, :Attr))
  end
end


# ob_generators(C::FinCatPresentation) = generators(presentation(C), :Ob)
# ob_generators(C::Union{FinCatPresentation{ThSchema.Meta.T},FinCatPresentation{ThPointedSetSchema.Meta.T}}) = let P = presentation(C)
#   vcat(generators(P, :Ob), generators(P, :AttrType))
# end

# hom_generators(C::Union{FinCatPresentation{ThSchema.Meta.T},FinCatPresentation{ThPointedSetSchema.Meta.T}}) = let P = presentation(C)
#   vcat(generators(P, :Hom), generators(P, :Attr))
# end

equations(C::FinCatPresentation) = equations(presentation(C))

# ob_generator(C::FinCatPresentation, x) = ob(C, presentation(C)[x])
# ob_generator(C::FinCatPresentation, x::GATExpr{:generator}) = ob(C, x)
# ob_generator_name(C::FinCatPresentation, x::GATExpr{:generator}) = first(x)

# hom_generator(C::FinCatPresentation, f) = hom(C, presentation(C)[f])
# hom_generator(C::FinCatPresentation, f::GATExpr{:generator}) = hom(C, f)
# hom_generator_name(C::FinCatPresentation, f::GATExpr{:generator}) = first(f)

# ob(C::FinCatPresentation, x::GATExpr) =
#   gat_typeof(x) == :Ob ? x : error("Expression $x is not an object")
# ob(C::Union{FinCatPresentation{ThSchema.Meta.T},FinCatPresentation{ThPointedSetSchema.Meta.T}}, x::GATExpr) =
#   gat_typeof(x) ∈ (:Ob, :AttrType) ? x :
#     error("Expression $x is not an object or attribute type")

# hom(C::FinCatPresentation, f) = hom_generator(C, f)
# hom(C::FinCatPresentation, fs::AbstractVector) =
#   mapreduce(f -> hom(C, f), compose, fs)
# hom(C::FinCatPresentation, f::GATExpr) =
#   gat_typeof(f) == :Hom ? f : error("Expression $f is not a morphism")
# hom(::Union{FinCatPresentation{ThSchema.Meta.T},FinCatPresentation{ThPointedSetSchema.Meta.T}}, f::GATExpr) =
#   gat_typeof(f) ∈ (:Hom, :Attr, :AttrType) ? f :
#     error("Expression $f is not a morphism or attribute")

id(C::Union{FinCatPresentation{ThSchema.Meta.T},FinCatPresentation{ThPointedSetSchema.Meta.T}}, x::AttrTypeExpr) = x
compose(C::Union{FinCatPresentation{ThSchema.Meta.T},FinCatPresentation{ThPointedSetSchema.Meta.T}}, f::AttrTypeExpr, g::AttrTypeExpr) =
  (f == g) ? f : error("Invalid composite of attribute type identities: $f != $g")


# # Use generator names, rather than generators themselves, for Dict keys. Enforced by FinDomFunctor constructor automatically.
ob_key(C::FinCatPresentation, x) = presentation_key(x)

hom_key(C::FinCatPresentation, f) = presentation_key(f)

presentation_key(name::Union{AbstractString,Symbol}) = name

presentation_key(expr::GATExpr{:generator}) = first(expr)

decompose(C::FinCatPresentation, f::GATExpr{:compose}) = args(f)

function Base.show(io::IO, C::FinCatPresentation)
  print(io, "FinCat(")
  show(io, presentation(C))
  print(io, ")")
end


end
