export FinCat, ob_generator, hom_generator,
  ob_generator_name, hom_generator_name, ob_generators, hom_generators,
  equations, is_discrete, is_free, edges, src, tgt, gentype, decompose, AbsCat

using StructEquality

using GATlab
import GATlab: equations, getvalue

import .....Theories: dom, codom, id, compose, ⋅, ∘
using .....Graphs
import .....Graphs: Graph, NamedGraph, src, tgt
using .....BasicSets: FinSet, SetOb

import ..Paths: Path

using ..Categories: ThCategoryExplicitSets, Cat
import ..Categories: ob_set, hom_set, obtype, homtype


# Theory of Finite Categories
#############################

"""
A FinCat has an unbiased `compose` method which must convert a path of 
generators into a Hom. (It is ok for Hom=Path, in which case this is a no-op).
One should also be able to express a hom in terms of generators (though this 
need not be unique, so `decompose` is a one-sided inverse).

This interface does NOT specify the fact that any implementation of FinCat 
should specify `equations`.

`Path` and `Set′` types are expected to be sent to Catlab's `Path` and `FinSet`.

The following laws are expected to hold:
  compose(emptyPath(a)) == id(a) ⊣ [a::Ob]
  compose(decompose(h)) == h ⊣ [(x,y)::Ob, a::Hom(x,y)]
  compose(a ++ b) = compose(compose(a), compose(b)) ⊣ [a::Path(x,y), b::Path(y,z)]
"""
@theory ThFinCat begin
  Ob::TYPE
  Hom(dom::Ob,codom::Ob)::TYPE; 
  id(a::Ob)::Hom(a,a)

  Gen(src::Ob,tgt::Ob)::TYPE; 
  
  Path′(p_src::Ob, p_tgt::Ob)::TYPE;
  compose(vgen::Path′(a,b))::Hom(a,b) ⊣ [(a,b)::Ob]
  decompose(h::Hom(a,b))::Path′(a,b) ⊣ [(a,b)::Ob]

  Set′::TYPE{FinSet}
  ob_set()::Set′
  gen_set()::Set′
end
  
ThFinCat.Meta.@wrapper FinCat

""" 
Common type for Categories and FinCats to be used by methods which only use 
their common interface. 
""" 
const AbsCat=Union{Cat, FinCat}


# Other methods
#--------------

Base.show(io::IO, C::FinCat) = show(io, getvalue(C))

""" synonym for `ob_set` """
ob_generators(f::FinCat)::FinSet = ob_set(f)

""" synonym for `gen_set` """
hom_generators(f::FinCat)::FinSet = gen_set(f)

obtype(c::FinCat)::Type = eltype(ob_set(c))

homtype(c::FinCat)::Type = impl_type(c, :Hom)

gentype(f::FinCat) = eltype(hom_generators(f))

hom_set(f::FinCat) = SetOb(impl_type(f, :Hom))

compose(c::FinCat, f, g) = compose(c, vcat(decompose(c, f), decompose(c, g)))

""" 
Create path from a vector of generators. If no s/t provided, then the list 
must not be empty 
"""
function Path(f::FinCat, gs::AbstractVector, s=nothing, t=nothing)
  s = isnothing(s) ? src(f, first(gs)) : s
  t = isnothing(t) ? tgt(f, last(gs)) : t
  Path(isempty(gs) ? gentype(f)[] : gs, s, t)
end

""" Is the category discrete?

A category is *discrete* if it is has no non-identity morphisms.
"""
is_discrete(C::FinCat) = isempty(hom_generators(C))

# Second clause should be superfluous, but we'll include it anyway.
Base.isempty(C::FinCat) = isempty(ob_generators(C)) && isempty(hom_generators(C))

# Equations #
#------------
""" Is the category freely generated?
"""
is_free(C::FinCat) = isempty(equations(C))

equations(f::FinCat) = equations(getvalue(f))

# Conversion to Graphs #
#-----------------------
"""
Graph underlying a finitely presented category whose object and hom generators 
are indexable, other than one explicitly generated by a graph.
"""
function NamedGraph(C::FinCat)
  Ob, Gen = obtype(C), gentype(C)
  g = NamedGraph{Ob,Gen}()
  obgens = collect(ob_generators(C))
  homgens = collect(hom_generators(C))
  add_vertices!(g,length(obgens);vname=obgens)
  s(f) = only(indexin([src(C,f)],obgens))
  t(f) = only(indexin([tgt(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens];
              ename=homgens) 
  g
end

function Graph(C::FinCat) 
  g = Graph()
  obgens = collect(ob_generators(C))
  homgens = collect(hom_generators(C))
  add_vertices!(g,length(obgens))
  s(f) = only(indexin([src(C,f)],obgens))
  t(f) = only(indexin([tgt(C,f)],obgens))
  add_edges!(g,Int[s(f) for f in homgens],Int[t(f) for f in homgens]) 
  return g
end

