
# Categories on graphs
######################

# Paths in graphs
#----------------

""" Path in a graph.

The path is allowed to be empty but always has definite start and end points
(source and target vertices).
"""
@struct_hash_equal struct Path{V,E,Edges<:AbstractVector{E}}
  edges::Edges
  src::V
  tgt::V
end
edges(path::Path) = path.edges
src(path::Path) = path.src
tgt(path::Path) = path.tgt

function Path(g::HasGraph, es::AbstractVector)
  !isempty(es) || error("Nonempty edge list needed for nontrivial path")
  all(e -> has_edge(g, e), es) || error("Path has edges not contained in graph")
  Path(es, src(g, first(es)), tgt(g, last(es)))
end

function Path(g::HasGraph, e)
  has_edge(g, e) || error("Edge $e not contained in graph $g")
  Path(SVector(e), src(g,e), tgt(g,e))
end

function Base.empty(::Type{Path}, g::HasGraph, v::T) where T
  has_vertex(g, v) || error("Vertex $v not contained in graph $g")
  Path(SVector{0,T}(), v, v)
end

Base.reverse(p::Path) = Path(reverse(edges(p)), tgt(p), src(p))

function Base.vcat(p1::Path, p2::Path)
  tgt(p1) == src(p2) ||
    error("Path start/end points do not match: $(tgt(p1)) != $(src(p2))")
  Path(vcat(edges(p1), edges(p2)), src(p1), tgt(p2))
end

coerce_path(::HasGraph, path::Path) = path

coerce_path(g::HasGraph, x) = Path(g, x)

function Base.show(io::IO, path::Path)
  print(io, "Path(")
  show(io, edges(path))
  print(io, ": $(src(path)) → $(tgt(path)))")
end

# Common interface for NamedGraphs and other graphs
#--------------------------------------------------
get_ob(g::NamedGraph, v) = g[v, :vname]

get_ob(::HasGraph, v) = v 

get_hom(::NamedGraph, e) = g[e, :ename]

get_hom(g::HasGraph, e) = e


# FinCatGraph
#------------

""" Abstract type for category backed by finite generating graph.

Edges are presumably morphism generators, and paths are the morphisms.
"""
abstract type FinCatGraph{G,V,E} <: FinCatImpl{V,Path{V,E},E} end

@instance ThFinCat{V,Path{V,E},E,Any} [model::FinCatGraph{G,V,E}] where {G,V,E} begin
  dom(f::Path{V,E}) = get_ob(getvalue(model), src(f))

  codom(f::Path{V,E}) = get_ob(getvalue(model),tgt(f))

  id(x::V) = empty(Path, getvalue(model), x)

  compose(f::Path{V,E},g::Path{V,E}) = vcat(f, g)

  singleton(f::E) = Path(getvalue(model), f)

  ob_generators() = let m = getvalue(model); get_ob.(Ref(m), vertices(m)) end

  hom_generators() = let m = getvalue(model); get_hom.(Ref(m), edges(m)) end
end


function Base.show(io::IO, C::FinCatGraph)
  print(io, "FinCat(")
  show(io, getvalue(C))
  print(io, ", [")
  join(io, equations(C), ", ")
  print(io, "])")
end

decompose(::FinCatGraph, path::Path) = edges(path)

# Free category on graph
#-----------------------

""" Free category generated by a finite graph.

The objects of the free category are vertices in the graph and the morphisms are
(possibly empty) paths.
"""
@struct_hash_equal struct FreeCatGraph{G<:HasGraph, V, E} <: FinCatGraph{G,V,E}
  graph::G
end

function FreeCatGraph(n::T) where {V,E,T<:NamedGraph{V,E}}
  FreeCatGraph{T,V,E}(n)
end

function FreeCatGraph(n::T) where {T<:HasGraph}
  FreeCatGraph{T, Int, Int}(n)
end

getvalue(g::FreeCatGraph) = g.graph

function Base.show(io::IO, C::FreeCatGraph)
  print(io, "FinCat(")
  show(io, getvalue(C))
  print(io, ")")
end

# Category on graph with equations
#---------------------------------

""" Category presented by a finite graph together with path equations.

The objects of the category are vertices in the graph and the morphisms are
paths, quotiented by the congruence relation generated by the path equations.
See (Spivak, 2014, *Category theory for the sciences*, §4.5).
"""
@struct_hash_equal struct FinCatGraphEq{
    G<:HasGraph,V,E,Eqs<:AbstractVector{<:Pair}} <: FinCatGraph{G, V, E}
  graph::G
  equations::Eqs
end

getvalue(f::FinCatGraphEq) = f.graph

equations(C::FinCatGraphEq) = C.equations

function FinCatGraph(g::G, eqs::AbstractVector=[]) where {G<:HasGraph}
  isempty(eqs) && return FreeCatGraph(g)
  eqs = process_eqs(g, eqs)
  FinCatGraphEq{G, Int,Int,typeof(eqs)}(g, eqs)
end

function FinCatGraph(g::NamedGraph{V,E}, eqs::AbstractVector=[]) where {V,E}
  isempty(eqs) && return FreeCatGraph(g)
  eqs = process_eqs(g, eqs)
  FinCatGraphEq{G, V,E,typeof(eqs)}(g, eqs)
end

FinCat(g::HasGraph, args...; kw...) = FinCat(FinCatGraph(g, args...; kw...))

process_eqs(g, eqs) = map(eqs) do eq
  lhs, rhs = coerce_path(g, first(eq)), coerce_path(g, last(eq))
  (src(lhs) == src(rhs) && tgt(lhs) == tgt(rhs)) ||
    error("Paths $lhs and $rhs in equation do not have equal (co)domains")
  lhs => rhs
end