include("SkelFinSetCat/Limits.jl")
include("SkelFinSetCat/Colimits.jl")
include("FinSetCat/Limits.jl")
include("FinSetCat/Colimits.jl")
include("VarFunctions.jl")
# include("SetCats/Subsets.jl")
# include("SetCats/SetCLimits.jl")
# include("SetCats/FinCLimits.jl")
# include("SetCats/VarFnLimits.jl")
