name: Julia CI/CD

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: "Action"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - release
      version:
        description: "Tag and release version:"
        required: false

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  discussions: read
  issues: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  CI:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.action == 'test')
    uses: AlgebraicJulia/.github/.github/workflows/julia_ci.yml@main
    secrets: inherit
  CompatHelper:
    if: github.event_name == 'schedule'
    uses: AlgebraicJulia/.github/.github/workflows/julia_compat.yml@main
    secrets: inherit
  Release:
    if: github.event_name == 'workflow_dispatch' && inputs.action == 'release' && inputs.version != ''
    uses: AlgebraicJulia/.github/.github/workflows/julia_release.yml@main
    secrets: inherit
