name: Auto Review Request

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  review-request:
    name: Review Request
    runs-on: ubuntu-latest
    steps:
      - uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
